version: '3.8'

services:
  data-report-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - MAX_MEMORY_MB=2048
      - MEMORY_WARNING_THRESHOLD_MB=1500
      - DATA_DIRECTORY=/app/data
      - ENVIRONMENT=production
    restart: unless-stopped
    depends_on:
      - nginx
    networks:
      - data-report-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/var/www/static
      - ./logs:/var/log/nginx
    depends_on:
      - data-report-app
    networks:
      - data-report-network
    restart: unless-stopped

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - data-report-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    networks:
      - data-report-network
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  data-report-network:
    driver: bridge